name: PR comments

on:
  pull_request:
    branches: ["*"]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
     - env:
        pr_number: ${{ github.event.pull_request.number }}
      run: |
       gh pr $pr_number issue comment 12 --body "Hi from GitHub CLI"
        

      