name: PR comments

on:
  pull_request:
    branches: ["*"]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            export body=$(curl ifconfig.co/json)
            export ip=$(echo $body | jq '.ip')
            epoort country=$(echo $body | jq '.country')
            gh pr comment $PR_NUMBER --body "this was run from addreas: $ip located at $country" --repo $GITHUB_REPOSITORY

        